import './globals.css'
import Navbar from '../components/nav/page';
import Footer from '@/components/footer/footer';
import { useRouter } from 'next/router';
import { Providers } from '@/components/ui/provider';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">

      <head />

      <body>
        <Providers>

        <Navbar />
        {children}

        </Providers>
      </body>
    </html>
  )
}